version: 2
updates:
  - package-ecosystem: cargo
    directory: '/wasm-set-start/'
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: '/wasm-multi-value-reverse-polyfill/'
    schedule:
      interval: weekly
